version: '2'

services:

  storage:
    build: storage-container/

  master:
    build: .
    volumes_from:
      - storage
    ports:
      - 11000:11000
      - 10889
    command: -shard Master

  caves:
    build: .
    volumes_from:
      - storage
    ports:
      - 11001:11001
    command: -shard Caves
    links:
      - master
